name: Django CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/cicd_backend_bakht

            echo "✅ Pulling latest code..."
            git config pull.rebase false
            git pull origin main

            echo "✅ Activating virtual environment..."
            source venv/bin/activate

            echo "✅ Installing dependencies..."
            pip install -r requirements.txt

            echo "✅ Running migrations..."
            python manage.py makemigrations
            python manage.py migrate

            echo "✅ Collecting static files..."
            python manage.py collectstatic --noinput

            echo "✅ Restarting Apache..."
            sudo systemctl restart apache2
